version: '3'
services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "4565-4599:4565-4599"
      - "8080:8080"
    environment:
      - PORT_WEB_UI=9090
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=0
      - HOST_TMP_FOLDER=${TMPDIR}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"