service: awssamplesneycore-serverless-apigateway

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    autostart: true
    lambda:
      mountCode: False
    docker:
      sudo: False
#    endpoints:
#      # This section is optional - can be used for customizing the target endpoints
#      S3: http://localhost:4566
#      DynamoDB: http://localhost:4566
#      CloudFormation: http://localhost:4566
#      Elasticsearch: http://localhost:4566
#      ES: http://localhost:4566
#      SNS: http://localhost:4566
#      SQS: http://localhost:4566
#      Lambda: http://localhost:4566
#      Kinesis: http://localhost:4566

provider:
  deploymentBucket:
    name: ${env:localstackBucket}
  name: aws
  runtime: dotnetcore2.1

package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    package:
      artifact: bin/release/netcoreapp2.1/hello.zip
    events:
      - http:
          path: hello
          method: get