service: awssamplesneycore-serverless-basic

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    autostart: true
    lambda:
      mountCode: False
    docker:
      sudo: False

provider:
  deploymentBucket:
    name: ${env:localstackBucket}
  name: aws
  runtime: dotnetcore2.1

package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    package:
      artifact: bin/release/netcoreapp2.1/hello.zip